FROM nginx:alpine

COPY frontend/dist /usr/share/nginx/html

RUN echo 'server {' \
    '  listen 80 default_server;' \
    '  server_name _;' \
    '  location / {' \
    '    root /usr/share/nginx/html;' \
    '    index index.html;' \
    '    try_files $uri $uri/ /index.html;' \
    '  }' \
    '  location /api/ {' \
    '    proxy_pass http://api:8080/api/;' \
    '    proxy_http_version 1.1;' \
    '    proxy_set_header Connection "";' \
    '    proxy_set_header Host $host;' \
    '    proxy_set_header X-Real-IP $remote_addr;' \
    '    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;' \
    '    client_max_body_size 500M;' \
    '  }' \
    '}' > /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
