FROM alpine:3.20

WORKDIR /app

RUN apk add --no-cache ca-certificates tzdata

COPY bin/api_linux /app/bin/api
COPY migrations /app/migrations

RUN chmod +x /app/bin/api

EXPOSE 8080

ENTRYPOINT ["/app/bin/api"]
