# syntax=docker/dockerfile:1
# Build Stage
FROM golang:alpine AS builder

WORKDIR /app

RUN apk add --no-cache git ca-certificates

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-w -s" -o /app/bin/api ./cmd/api

# Final Stage
FROM alpine:3.20

WORKDIR /app

RUN apk add --no-cache ca-certificates tzdata

COPY --from=builder /app/bin/api /app/bin/api
COPY --from=builder /app/migrations /app/migrations
COPY .env.example /app/.env

EXPOSE 8080

ENTRYPOINT ["/app/bin/api"]
