# syntax=docker/dockerfile:1
# Build Stage
FROM golang:alpine AS builder

WORKDIR /app

RUN apk add --no-cache git ca-certificates

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-w -s" -o /app/bin/worker ./cmd/worker

# Final Stage
FROM alpine:3.20

WORKDIR /app

RUN apk add --no-cache ffmpeg ca-certificates tzdata

COPY --from=builder /app/bin/worker /app/bin/worker
COPY --from=builder /app/migrations /app/migrations

RUN mkdir -p /tmp/transcription-jobs

ENTRYPOINT ["/app/bin/worker"]
